spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: lb://accounts
              predicates:
                - Path=/api/v1/bank/accounts/**
            - id: movements
              uri: lb://movements
              predicates:
                - Path=/api/v1/bank/movements/**
            - id: loans
              uri: lb://loans
              predicates:
                - Path=/api/v1/bank/loans/**