spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: lb://accounts
              predicates:
                - Path=/api/v1/bank/accounts/**
            - id: transfers
              uri: lb://transfers
              predicates:
                - Path=/api/v1/bank/transfers/**
            - id: loans
              uri: lb://loans
              predicates:
                - Path=/api/v1/bank/loans/**